[tool.ruff]
ignore = [
    "E501",
    "F401",
    "F403",
    "W605",
]
# Same as black
line-length = 88
select = [
    "B",
    "B9",
    "C",
    "E",
    "F",
    "I",
    "W",
]

target-version = "py39"

[tool.ruff.mccabe]
max-complexity = 18

